
max_obstacle_height: 2.0
min_obstacle_height: -1.0

use_dijkstra: false
visualize_potential: false

robot_base_frame: base_footprint
footprint: [[0.49, 0.37], [0.49, -0.37], [0.34, -0.51], [-0.34, -0.51], [-0.49, -0.37], [-0.49, 0.37], [-0.34, 0.51], [0.34, 0.51]]
