
controller_frequency: 2.0
planner_frequency: 2.0
recovery_behaviour_enabled: true

NavfnROS:
  allow_unknown: false # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

DWAPlannerROS:
  # Robot configuration parameters
  acc_lim_th: 10.8
  acc_lim_x: 10.5
  acc_lim_y: 0.0

  max_vel_x: 1.8
  min_vel_x: 0.0
  max_vel_y: 0
  min_vel_y: 0

  max_trans_vel: 2.5
  min_trans_vel: 0.1
  max_rot_vel: 2.0
  min_rot_vel: 0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.5
  latch_xy_goal_tolerance: true

  # Forward Simulation Parameters
  sim_time: 1.0
  sim_granularity: 0.02
  vx_samples: 12
  vy_samples: 0
  vtheta_samples: 20
  penalize_negative_x: false

EBandPlannerROS:
  # Robot configuration parameters
  max_acceleration: 5.8
  virtual_mass: 0.75
  max_translational_acceleration: 5.0
  max_rotational_acceleration: 5.0

  max_vel_lin: 1.8
  min_vel_lin: 0.0
  max_vel_th: 1.2
  min_vel_th: 0.1

  max_trans_vel: 1.8
  min_trans_vel: 0.1
  max_rot_vel: 1.0
  min_rot_vel: 0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.3
  latch_xy_goal_tolerance: true
