
inflation_radius: 0.01

max_obstacle_height: 2.0
min_obstacle_height: -1.0

use_dijkstra: false
visualize_potential: false

# name of the frame at base-link of the spencer robot
robot_base_frame: base_footprint
# specifications for the footprint of the robot as polygon (in meters)
footprint: [[0.39, 0.27], [0.39, -0.27], [0.24, -0.41], [-0.24, -0.41], [-0.39, -0.27], [-0.39, 0.27], [-0.24, 0.41], [0.24, 0.41]]

